#Audio Input
sample_rate: 16000
block_size: 80
channels: 1
ring_buffer_chunks: 20

#Wakeword Detector
model_path: "models/wakeword/alexa_v0.1.onnx"
threshold: 0.5
vad_threshold: 0.5

#Speech Recognition
model_name: "models/stt/faster-whisper-small"
device: "cpu"
compute_type: "int8"
language: "de"
beam_size: 5
silence_threshold: 400.0
silence_blocks: 15

#LLM

#Text to Speech
